### ISSUE TITLE
Artwork image missing

### ISSUE THREAD

**Issue by ldldylan** [ldldylan/PixelPanda#15]
![image](https://user-images.githubusercontent.com/47541760/228107522-b1af056d-7e9e-41d5-8892-3ce023238356.png)

**Comment by ldldylan** [comment]
![image](https://user-images.githubusercontent.com/47541760/228108317-70853ab7-f026-4ccf-baa7-be91f67650a2.png)

**Comment by kennytram** [comment]
It seems to be related to 0.png issue. Probably when someone tried to upload an invalid file when doing postman. Try reseeding the images again, or delete it from the invalid image from the collection.
