### ISSUE TITLE
Console errors and blank page after logging out

### ISSUE THREAD

**Issue by ldldylan** [ldldylan/PixelPanda#16]
It happens sometimes on live site

**Comment by ldldylan** [comment]
It happens sometimes on live site

**Comment by kennytram** [comment]
It happens when you click back after signing out from an artwork's page.

**Comment by ldldylan** [comment]
![image](https://user-images.githubusercontent.com/47541760/228108276-175b0ae3-3c20-455e-8281-8c514bd3782a.png)

**Comment by kennytram** [comment]
Fixed in the pull request.
